name: Auto-Tag on Version Change (Reusable)

on:
  workflow_call:

permissions:
  contents: write

# A GitHub action cannot push to JuliaRegistry from another repo without a PAT
# REGISTRY_PAT is a ClimFlows PAT granting read/write acces to JuliaRegistry
# It has been stored as an org-wide secret.

# The PAT must have read/write permissions for Contents
# Not sure the `git-credentials` bit is needed, but this is working after many attempts
# that were failing due to insufficient PAT permissions.

env:
  JULIA_GIT: /usr/bin/git
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_PAT: ${{ secrets.REGISTRY_PAT }}
  REGISTRY_PATH: /home/runner/.julia/registries/ClimFlowsRegistry

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if version from Project.toml is tagged
        id: version
        run: |
          VERSION=$(julia -e 'using TOML; println(TOML.parsefile("Project.toml")["version"])')
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Version $VERSION is already tagged, skipping registration."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version $VERSION is not tagged yet, proceeding to registration."
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi
      - name: Configure git, register package and push tag
        if: steps.version.outputs.exists == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.REGISTRY_PAT }}@github.com" > ~/.git-credentials
          julia --project=@register -e '
            using Pkg; Pkg.add("LocalRegistry")
            using LocalRegistry
            Pkg.Registry.add(RegistrySpec(url="https://github.com/ClimFlows/JuliaRegistry.git/"))
            register(pwd() ; registry="ClimFlowsRegistry", push=false)
          '
          git -C $REGISTRY_PATH remote set-url origin "https://x-access-token:${{ secrets.REGISTRY_PAT }}@github.com/ClimFlows/JuliaRegistry.git"
          git -C $REGISTRY_PATH push origin master
          echo "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
