name: Tests (reusable)

on:
  workflow_call:
    inputs:
      version: 
        description: "Julia version on which to run tests"
        required: true
        type: string
      downgrade_version: 
        description: "Julia version on which to try old dependencies"
        required: false
        type: string
        default: '1.10'
      arch:
        description: "Architecture on which to run tests"
        required: false
        type: string
        default: x64
      os:
        description: "OS on which to run tests"
        required: false
        type: string
        default: ubuntu-latest

jobs:
  test:
    name: Julia ${{ inputs.version }} - ${{ inputs.os }} - ${{ inputs.arch }} - ${{ github.event_name }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    # This job is able to run julia-downgrade-compat@v2 even when
    # some package dependencies are registered in the ClimFlows registry.
    # For this the registry is added before 'downgrade' and after 'cache'
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ inputs.version }}
          arch: ${{ inputs.arch }}
          include-all-prereleases: true
      - uses: julia-actions/cache@v2
        with:
          cache-name: 'julia-cache;workflow=${{ github.workflow }};job=${{ github.job }};os=${{ inputs.os }};version=${{ inputs.version }};arch=${{ inputs.arch }}'
      - name: Add private registry
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.Registry.add()
          url = "https://github.com/ClimFlows/JuliaRegistry.git"
          Pkg.Registry.add(RegistrySpec(; url))
      - uses: julia-actions/julia-downgrade-compat@v2
        if: ${{ inputs.version == inputs.downgrade_version }}
        with:
          skip: Pkg, TOML
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_EXCLUSIVE: 1
          JULIA_NUM_THREADS: 2
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false  # or true if you want CI to fail when Codecov fails
          files: lcov.info
